### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Seunghyeon-Cho**

### CODE REVIEW

**Comment by yunho0130** [comment]
@pmcsh04 Please resolve branch conflicts. Update your local repo and PR again.

**Review by yunho0130 — COMMENTED** [review]
@pmcsh04 Please check the latest version of this repository

**Review by yunho0130 — CHANGES_REQUESTED** [review]
Please resolve conflict

**Comment by pmcsh04** [comment]
README.md

**Comment by pmcsh04** [comment]
README.md

**Comment by yunho0130** [comment]
This PR still has a conflict.

**Review by yunho0130 — CHANGES_REQUESTED** [review]
This PR still has a conflict.

**Comment by pmcsh04** [comment]
change

**Pull request closed without merging**
